automerge: false
files:
  $actions/aireos.py:
    labels: aireos cisco networking
  $actions/aruba.py:
    maintainers: $team_aruba
    labels: aruba networking
  $actions/ironware.py:
    maintainers: paulquack
    labels: ironware networking
  $actions/nos_config.py:
    labels: nos
  $actions/sros.py:
    maintainers: $team_networking
    labels: networking sros
  $cliconfs/:
    labels: networking
  $cliconfs/aruba.py:
    maintainers: $team_aruba
    labels: aruba networking
  $cliconfs/ce.py:
    maintainers: $team_huawei
    labels: ce cloudengine huawei networking
  $cliconfs/edgeswitch.py:
    maintainers: f-bor
    labels: edgeswitch networking
  $cliconfs/eric_eccli.py:
    maintainers: $team_networking itercheng
    labels: eric_eccli networking
  $cliconfs/exos.py:
    maintainers: $team_extreme rdvencioneck
    labels: exos networking
  $cliconfs/ironware.py:
    maintainers: paulquack
    labels: ironware networking
  $cliconfs/nos.py:
    maintainers: $team_extreme
    labels: networking nos
  $cliconfs/slxos.py:
    maintainers: $team_extreme
    labels: networking slxos
  $cliconfs/voss.py:
    maintainers: $team_extreme
    labels: networking voss
  $httpapis/:
    maintainers: $team_networking
    labels: networking
  $httpapis/exos.py:
    maintainers: $team_networking LindsayHill ujwalkomarla
    labels: exos networking
  $httpapis/ftd.py:
    maintainers: $team_networking annikulin
    labels: cisco ftd networking
    keywords: firepower ftd
  $module_utils/network/a10/a10.py:
    maintainers: ericchou1 mischapeters
    labels: networking
  $module_utils/network/aireos/aireos.py:
    labels: cisco networking
  $module_utils/network/aos/aos.py:
    maintainers: dgarros jeremyschulman
    labels: networking
  $module_utils/network/apconos/apconos.py:
    labels: networking
  $module_utils/network/aruba/aruba.py:
    maintainers: $team_aruba
    labels: networking
  $module_utils/network/avi/:
    maintainers: $team_avi
    labels: networking
  $module_utils/network/bigswitch/bigswitch.py:
    maintainers: jayakody tedelhourani vuile
    labels: networking
  $module_utils/network/cloudengine/ce.py:
    maintainers: $team_huawei
    labels: huawei networking
  $module_utils/network/cnos/:
    ignore: amuraleedhar dkasberg
    maintainers: $team_lenovo
    labels: networking
  $module_utils/network/edgeos/edgeos.py:
    labels: networking
  $module_utils/network/edgeswitch/:
    maintainers: f-bor
    labels: networking
  $module_utils/network/enos/enos.py:
    maintainers: amuraleedhar
    labels: networking
  $module_utils/network/eric_eccli/eric_eccli.py:
    maintainers: $team_networking itercheng
    labels: networking
  $module_utils/network/exos/:
    maintainers: $team_extreme rdvencioneck
    labels: networking
  $module_utils/network/f5/:
    maintainers: caphrim007 wojtek0806
    labels: networking
  $module_utils/network/ftd/:
    maintainers: $team_ftd
    labels: cisco networking
    keywords: firepower ftd
  $module_utils/network/:
    labels: networking
  $module_utils/network/ironware/ironware.py:
    maintainers: paulquack
    labels: networking
  $module_utils/network/netscaler/netscaler.py:
    maintainers: $team_netscaler
    labels: networking
  $module_utils/network/netvisor/:
    labels: networking
  $module_utils/network/nos/nos.py:
    maintainers: $team_extreme
    labels: networking
  $module_utils/network/ordnance/ordnance.py:
    maintainers: alexanderturner djh00t
    labels: networking
  $module_utils/network/slxos/slxos.py:
    maintainers: $team_extreme
    labels: networking
  $module_utils/network/sros/sros.py:
    labels: networking
  $module_utils/network/voss/voss.py:
    maintainers: $team_extreme
    labels: networking

  $modules/network/a10/a10_server_axapi3.py:
    authors: ericchou1
    maintainers: mischapeters
  $modules/network/a10/:
    authors: ericchou1 mischapeters
  $modules/network/aireos/:
    authors: jmighion
    labels: cisco networking
    ignore: jmighion
  $modules/network/apconos/apconos_command.py:
    authors: davidlee-ap
  $modules/network/aruba/:
    authors: jmighion
    maintainers: $team_aruba
    ignore: jmighion
  $modules/network/avi/:
    authors: grastogi23
    maintainers: ericsysmin khaltore
  $modules/network/avi/avi_api_version.py:
    authors: vivobg
    maintainers: $team_avi
  $modules/network/avi/avi_autoscalelaunchconfig.py:
    authors: chaitanyaavi
    maintainers: $team_avi
  $modules/network/avi/avi_l4policyset.py:
    authors: chaitanyaavi
    maintainers: $team_avi
  $modules/network/avi/avi_user.py:
    authors: gitshrikant
    maintainers: $team_avi
  $modules/network/avi/avi_useraccount.py:
    authors: chaitanyaavi
    maintainers: $team_avi
  $modules/network/bigswitch/:
    authors: tedelhourani
    maintainers: jayakody vuile
  $modules/network/check_point/checkpoint_access_layer_facts.py:
    authors: rcarrillocruz
    labels: checkpoint_access_layer_facts
  $modules/network/check_point/checkpoint_access_rule.py:
    authors: rcarrillocruz
    labels: checkpoint_access_rule
  $modules/network/check_point/checkpoint_access_rule_facts.py:
    authors: rcarrillocruz
    labels: checkpoint_access_rule_facts
  $modules/network/check_point/checkpoint_host.py:
    authors: rcarrillocruz
    labels: checkpoint_host
  $modules/network/check_point/checkpoint_host_facts.py:
    authors: rcarrillocruz
    labels: checkpoint_host_facts
  $modules/network/check_point/checkpoint_object_facts.py:
    authors: rcarrillocruz
    labels: checkpoint_object_facts
  $modules/network/check_point/checkpoint_run_script.py:
    authors: rcarrillocruz
    labels: checkpoint_run_script
  $modules/network/check_point/checkpoint_session.py:
    authors: rcarrillocruz
    labels: checkpoint_session
  $modules/network/check_point/checkpoint_task_facts.py:
    authors: rcarrillocruz
    labels: checkpoint_task_facts
  $modules/network/check_point/cp_publish.py:
    authors: chkp-orso
    labels: cp_publish
  $modules/network/cloudengine/:
    authors: QijunPan
    maintainers: TommyLike edisonxiang freesky-edward hwDCN niuzhenguo xuxiaowei0512 yanzhangi zengchen1024 zhongjun2
    labels: huawei networking
  $modules/network/cloudengine/ce_command.py:
    authors: CloudEngine-Ansible
    maintainers: $team_huawei
  $modules/network/cloudengine/ce_multicast_global.py:
    authors: xuxiaowei0512
    maintainers: QijunPan TommyLike edisonxiang freesky-edward hwDCN niuzhenguo yanzhangi zengchen1024 zhongjun2
  $modules/network/cloudengine/ce_multicast_igmp_enable.py:
    authors: CloudEngine-Ansible
    maintainers: $team_huawei
  $modules/network/cloudengine/ce_static_route_bfd.py:
    authors: CloudEngine-Ansible
    maintainers: $team_huawei
  $modules/network/cloudengine/ce_vrrp.py:
    authors: numone213
    maintainers: $team_huawei
  $modules/network/cloudvision/cv_server_provision.py:
    authors: mharista
  $modules/network/cnos/:
    ignore: amuraleedhar dkasberg
    maintainers: $team_lenovo
  $modules/network/cumulus/nclu.py:
    authors: isharacomix
    maintainers: jrrivers
  $modules/network/edgeos/edgeos_command.py:
    authors: beardymcbeards samdoran
  $modules/network/edgeos/:
    authors: Qalthos samdoran
  $modules/network/edgeswitch/:
    authors: f-bor
  $modules/network/enos/:
    authors: amuraleedhar
  $modules/network/eric_eccli/eric_eccli_command.py:
    authors: itercheng
  $modules/network/exos/exos_command.py:
    authors: rdvencioneck
    maintainers: $team_extreme
  $modules/network/exos/exos_config.py:
    authors: hlrichardson
    maintainers: $team_extreme rdvencioneck
  $modules/network/exos/exos_facts.py:
    authors: hlrichardson ujwalkomarla
    maintainers: LindsayHill rdvencioneck
  $modules/network/exos/exos_l2_interfaces.py:
    authors: jayalakshmiV
    maintainers: $team_extreme rdvencioneck
  $modules/network/exos/exos_lldp_global.py:
    authors: ujwalkomarla
    maintainers: LindsayHill rdvencioneck
  $modules/network/exos/exos_lldp_interfaces.py:
    authors: JayalakshmiV
    maintainers: $team_extreme rdvencioneck
  $modules/network/exos/exos_vlans.py:
    authors: jayalakshmiV
    maintainers: $team_extreme rdvencioneck
  $modules/network/f5/:
    authors: caphrim007 wojtek0806
    ignore: JoeReifel Qalthos ganeshrn mhite perzizzle srgvg
  $modules/network/f5/bigip_facts.py:
    authors: caphrim007 mhite
    maintainers: wojtek0806
  $modules/network/f5/bigip_gtm_facts.py:
    authors: caphrim007
    maintainers: wojtek0806
  $modules/network/f5/bigiq_device_facts.py:
    authors: caphrim007
    maintainers: wojtek0806
  $modules/network/ftd/:
    authors: annikulin
    labels: cisco networking
    keywords: firepower ftd
  $modules/network/icx/:
    authors: Commscope
    maintainers: sushma-alethea
  $modules/network/illumos/:
    authors: xen0l
    maintainers: bcoca danowar2k fishman jasperla jpdasma mator scathatheworm troy2914
    labels: solaris
    keywords: beadm dladm illumos ipadm nexenta omnios openindiana pfexec smartos solaris sunos zfs zpool
  $modules/network/ingate/:
    authors: ingatesystems
  $modules/network/ironware/:
    authors: paulquack
  $modules/network/itential/:
    authors: cma0
  $modules/network/netact/netact_cm_command.py:
    authors: hatuomin
  $modules/network/netscaler/:
    authors: giorgos-nikolopoulos
    maintainers: chiradeep
  $modules/network/netvisor/:
    authors: rajaspachipulusu17
    maintainers: $team_netvisor
  $modules/network/nos/:
    authors: LindsayHill
    maintainers: ujwalkomarla
  $modules/network/nuage/nuage_vspk.py:
    authors: pdellaert
  $modules/network/opx/opx_cps.py:
    authors: skg-net
  $modules/network/ordnance/:
    authors: alexanderturner
    maintainers: djh00t
  $modules/network/radware/:
    authors: evgenyfedoruk
  $modules/network/slxos/:
    authors: bigmstone
    maintainers: LindsayHill ujwalkomarla
    ignore: bigmstone
  $modules/network/slxos/slxos_vlan.py:
    authors: lindsayhill
    maintainers: $team_extreme
  $modules/network/sros/:
    authors: privateip
  $modules/network/voss/:
    authors: LindsayHill
  $terminals/:
    labels: networking
  $terminals/aruba.py:
    maintainers: $team_aruba
    labels: aruba networking
  $terminals/ce.py:
    maintainers: $team_huawei
    labels: ce cloudengine huawei networking
  $terminals/edgeos.py:
    maintainers: samdoran
    labels: edgeos networking
  $terminals/edgeswitch.py:
    maintainers: f-bor
    labels: edgeswitch networking
  $terminals/eric_eccli.py:
    maintainers: itercheng
    labels: eric_eccli networking
  $terminals/exos.py:
    maintainers: $team_extreme rdvencioneck
    labels: exos networking
  $terminals/ironware.py:
    maintainers: paulquack
    labels: ironware networking
  $terminals/nos.py:
    maintainers: $team_extreme
    labels: networking nos
  $terminals/slxos.py:
    maintainers: $team_extreme
    labels: networking slxos
  $terminals/sros.py:
    maintainers: $team_networking
    labels: networking sros
  $terminals/voss.py:
    maintainers: $team_extreme
    labels: networking voss


macros:
  actions: plugins/action
  becomes: plugins/become
  callbacks: plugins/callback
  cliconfs: plugins/cliconf
  connections: plugins/connection
  doc_fragments: plugins/doc_fragments
  filters: plugins/filter
  httpapis: plugins/httpapi
  inventories: plugins/inventory
  lookups: plugins/lookup
  module_utils: plugins/module_utils
  modules: plugins/modules
  terminals: plugins/terminal
  team_aci: aciguru brunocalogero devarshishah3 fadallar jmcgill298 koladiya mtorelli rsmeyers schunduri smnmtzgr
  team_aruba: karthikeyan-dhandapani
  team_avi: ericsysmin grastogi23 khaltore
  team_e_spirit: MatrixCrawler getjack
  team_extreme: LindsayHill ujwalkomarla
  team_ftd: annikulin
  team_huawei: QijunPan TommyLike edisonxiang freesky-edward hwDCN niuzhenguo xuxiaowei0512 yanzhangi zengchen1024 zhongjun2
  team_lenovo: istaicu mihaibroc
  team_netscaler: chiradeep giorgos-nikolopoulos
  team_netvisor: Qalthos amitsi csharpe-pn pdam preetiparasar
  team_networking: NilashishC Qalthos danielmellado ganeshrn justjais trishnaguha
  team_scaleway: DenBeke QuentinBrosse abarbare jerome-quere kindermoumoute remyleo
