namespace: community
name: network
version: 1.3.5
readme: README.md
authors:
  - Ansible (https://github.com/ansible)
description: null
license_file: COPYING
tags: [community, network]
# NOTE: No more dependencies can be added to this list
dependencies:
  ansible.netcommon: '>=1.0.0,<2.0.0'
  check_point.mgmt: '>=1.0.0'
  fortinet.fortios: '>=1.0.0'
repository: https://github.com/ansible-collections/community.network
documentation: https://docs.ansible.com/ansible/latest/collections/community/network/
homepage: https://github.com/ansible-collections/community.network
issues: https://github.com/ansible-collections/community.network/issues
