plugin_routing:
  modules:
    ali_instance_facts:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    online_server_facts:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    online_user_facts:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    one_image_facts:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    aci_intf_policy_fc:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    aci_intf_policy_l2:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    aci_intf_policy_lldp:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    aci_intf_policy_mcp:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    aci_intf_policy_port_channel:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    aci_intf_policy_port_security:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    bigip_asm_policy:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    bigip_device_facts:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    bigip_facts:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    bigip_gtm_facts:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    bigip_iapplx_package:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    bigip_security_address_list:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    bigip_security_port_list:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    bigip_traffic_group:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    bigiq_device_facts:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    pn_cluster:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    pn_ospf:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    pn_ospfarea:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    pn_show:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    pn_trunk:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    pn_vlag:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    pn_vlan:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    pn_vrouter:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    pn_vrouterbgp:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    pn_vrouterif:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    pn_vrouterlbif:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    panos_admin:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    panos_admpwd:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    panos_cert_gen_ssh:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    panos_check:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    panos_commit:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    panos_dag:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    panos_dag_tags:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    panos_import:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    panos_interface:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    panos_lic:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    panos_loadcfg:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    panos_match_rule:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    panos_mgtconfig:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    panos_nat_rule:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    panos_object:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    panos_op:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    panos_pg:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    panos_query_rules:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    panos_restart:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    panos_sag:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    panos_security_rule:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
    panos_set:
      deprecation:
        removal_date: TBD
        warning_text: see plugin documentation for details
